-- ============================================================================
-- MIGRATION 016: CRM WORK ITEMS, PRICING RULES & SALES QUOTES
-- ============================================================================

-- 1. CRM Client Work Items (Deliverables, Tickets, Onboarding & Projects)
CREATE TABLE IF NOT EXISTS crm_work_items (
  id TEXT PRIMARY KEY,
  tenantId TEXT NOT NULL,
  crmCompanyId TEXT,
  contactId TEXT,
  leadId TEXT,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL DEFAULT 'General',
  subcategory TEXT,
  assignedTeamId TEXT,
  assignedUserId TEXT,
  priority TEXT NOT NULL DEFAULT 'normal',
  status TEXT NOT NULL DEFAULT 'TODO',
  dueAt TEXT,
  completedAt TEXT,
  createdByUserId TEXT,
  createdAt TEXT NOT NULL DEFAULT '',
  updatedAt TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_crm_work_items_tenant ON crm_work_items("tenantId");
CREATE INDEX IF NOT EXISTS idx_crm_work_items_company ON crm_work_items("tenantId", "crmCompanyId");
CREATE INDEX IF NOT EXISTS idx_crm_work_items_user ON crm_work_items("tenantId", "assignedUserId");
CREATE INDEX IF NOT EXISTS idx_crm_work_items_status ON crm_work_items("tenantId", status);

-- 2. CRM Sales Pricing Rules (Configured by Company Owner per Tenant)
CREATE TABLE IF NOT EXISTS crm_pricing_rules (
  id TEXT PRIMARY KEY,
  "tenantId" TEXT NOT NULL UNIQUE,
  currency TEXT NOT NULL DEFAULT 'USD',
  "taxRate" NUMERIC(5,2) NOT NULL DEFAULT 0,
  "agentMaxDiscountPct" NUMERIC(5,2) NOT NULL DEFAULT 10,
  "teamLeadMaxDiscountPct" NUMERIC(5,2) NOT NULL DEFAULT 25,
  "packagesJson" TEXT NOT NULL,
  "addonsJson" TEXT NOT NULL,
  "perUserPriceMonthly" NUMERIC(10,2) NOT NULL DEFAULT 15.00,
  "perUserPriceAnnual" NUMERIC(10,2) NOT NULL DEFAULT 144.00,
  "updatedByUserId" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT '',
  "updatedAt" TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_crm_pricing_rules_tenant ON crm_pricing_rules("tenantId");

-- 3. CRM Quotes (Frozen snapshots of commercial quotes generated by agents)
CREATE TABLE IF NOT EXISTS crm_quotes (
  id TEXT PRIMARY KEY,
  "tenantId" TEXT NOT NULL,
  "quoteNumber" TEXT NOT NULL,
  "crmCompanyId" TEXT,
  "contactId" TEXT,
  "leadId" TEXT,
  "packageId" TEXT,
  "packageName" TEXT,
  "userCount" INTEGER NOT NULL DEFAULT 1,
  "billingCycle" TEXT NOT NULL DEFAULT 'monthly',
  currency TEXT NOT NULL DEFAULT 'USD',
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  "discountPct" NUMERIC(5,2) NOT NULL DEFAULT 0,
  "discountAmount" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "taxAmount" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "totalAmount" NUMERIC(12,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  notes TEXT,
  "validUntil" TEXT,
  "assignedUserId" TEXT,
  "createdByUserId" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT '',
  "updatedAt" TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_crm_quotes_tenant ON crm_quotes("tenantId");
CREATE INDEX IF NOT EXISTS idx_crm_quotes_company ON crm_quotes("tenantId", "crmCompanyId");
CREATE INDEX IF NOT EXISTS idx_crm_quotes_lead ON crm_quotes("tenantId", "leadId");
CREATE INDEX IF NOT EXISTS idx_crm_quotes_status ON crm_quotes("tenantId", status);

-- 4. CRM Quote Line Items (Granular snapshot of packages, add-ons, and seats)
CREATE TABLE IF NOT EXISTS crm_quote_items (
  id TEXT PRIMARY KEY,
  "tenantId" TEXT NOT NULL,
  "quoteId" TEXT NOT NULL,
  "itemType" TEXT NOT NULL,
  name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  "unitPrice" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "lineTotal" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "createdAt" TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_crm_quote_items_quote ON crm_quote_items("tenantId", "quoteId");
